// Copyright 2009 Google Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// ========================================================================

import "oaidl.idl";

[
  object,
  uuid(7487b5e1-fcdd-414e-b17c-30382ee8df30),
  dual,
  helpstring("GoogleUpdate3Web Control"),
  pointer_default(unique)
]
interface IGoogleUpdate3WebControl : IDispatch {
  [id(1)] HRESULT createOmahaMachineServerAsync(
      [in] VARIANT_BOOL create_elevated,
      [out, retval] IDispatch** async_status);

  [id(2)] HRESULT createOmahaUserServer([out, retval] IDispatch** server);

  [id(3)] HRESULT getInstalledVersion([in] BSTR guid_string,
                                      [in] VARIANT_BOOL is_machine,
                                      [out, retval] BSTR* version_string);

  [id(4)] HRESULT crossInstall([in] BSTR extra_args);

  [id(5)] HRESULT launchAppCommand([in] BSTR guid_string,
                                   [in] VARIANT_BOOL is_machine,
                                   [in] BSTR cmd_id);
};

[
  object,
  uuid(2c41ec7a-dedb-42c2-bd91-bb389d287809),
  dual,
  helpstring("Google Update OneClick Control"),
  pointer_default(unique)
]
interface IGoogleUpdateOneClick : IDispatch
{
  // Deprecated. Will be removed in the next release of OneClick.
  [id(1), helpstring("Install")] HRESULT Install(
      [in] BSTR cmd_line_args,
      [in] VARIANT* success_callback,
      [in] VARIANT* failure_callback);

  // New, easier way of calling Install. Use this for newer web pages.
  [id(2), helpstring("Install2")] HRESULT Install2([in] BSTR extra_args);

  [id(3), helpstring("GetInstalledVersion")] HRESULT GetInstalledVersion(
      [in] BSTR guid_string,
      [in] VARIANT_BOOL is_machine,
      [out, retval] BSTR* version_string);

  [id(4), helpstring("GetOneClickVersion")] HRESULT GetOneClickVersion(
      [out, retval] long* version);

  // TODO(omaha): Remove this if LaunchAppCommand only ships in Omaha3
  [id(5), helpstring("LaunchAppCommand")] HRESULT LaunchAppCommand(
      [in] BSTR app_guid,
      [in] VARIANT_BOOL is_machine,
      [in] BSTR cmd_id);
};

[
  uuid(f42e59df-6a66-4779-a472-3e63bc69b07d),
  version(1.0),
  helpstring("Omaha Browser Plugins 3.0 Type Library")
]
library GoogleUpdateControlLib {
  importlib("stdole2.tlb");

  interface IGoogleUpdateOneClick;
  interface IGoogleUpdate3WebControl;

  [
    uuid(98c2bd4f-9b16-4276-9e83-a6a9499cd40e),
    helpstring("Google Update OneClick Control Class")
  ]
  coclass GoogleUpdateOneClickControlCoClass
  {
    [default] interface IGoogleUpdateOneClick;
  };

  [
    uuid(f0089b78-7bd2-4748-b3a5-2fea03f8a875),
    helpstring("GoogleUpdate3Web Control Class")
  ]
  coclass GoogleUpdate3WebControlCoClass {
    [default] interface IDispatch;
  };
};
